server:
  port: ${PORT:0}
  servlet:
    context-path: /authentication

spring:
  application:
    name: sirius-authentication-server
#  cloud:
#    config:
#      uri: http://localhost:8761

  jpa:
    show-sql:  false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect        
    open-in-view: false
  jmx:
    enabled: false    
  datasource:
    url: jdbc:oracle:thin:@192.168.93.145:1521:XE
    username: autenticacao
    password: autenticacao
    driver-class-name: oracle.jdbc.OracleDriver
    initialization-mode: never
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    hostname: localhost    
    port: 8761
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

# zuul timeout 
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon: 
  ConnectTimeout: 10000
  ReadTimeout: 20000

# swagger
springfox:
  documentation:
    auto-startup: true
