INSERT INTO TBAUT_ROLE (ID,DSCOD,ICSIT,NOME) VALUES ('1','1','ATIVO','ADMIN');
INSERT INTO TBAUT_ROLE (ID,DSCOD,ICSIT,NOME) VALUES ('2','2','ATIVO','OPERADOR');

INSERT INTO TBAUT_USR (ID,DSCOD,ICSIT,EMAIL,NOME,PASSWORD) VALUES ('1','1','ATIVO','jossemar@gmail.com','Jossemar Ávila de Morais','123456');
INSERT INTO TBAUT_USR (ID,DSCOD,ICSIT,EMAIL,NOME,PASSWORD) VALUES ('2','2','ATIVO','gabriel@gmail.com','Gabriel Ávila de Morais','123456');

INSERT INTO TBAUT_USR_ROL (IDUSR,IDROL) VALUES ('1','1');
INSERT INTO TBAUT_USR_ROL (IDUSR,IDROL) VALUES ('2','2');
