package br.com.siriussoftware.suporte.admin.domain.chamado;

public enum SituacaoChamadoEnum {

	// SOMENTE PODE SER ABERTO PELO CLIENTE
	ABERTO,

	EM_ANALISE,

	EM_ATENDIMENTO,
	
	ATENDIMENTO_CONCLUIDO,

	// SOMENTE PODE SER FINALIZADO PELA SIRIUS (INDICA QUE FOI FINALIZADO E NÃO SERÁ ATENDIDO)
	FINALIZADO,
	
	// SOMENTE PODE SER CLASSIFICADO PELA SIRIUS ( INDICA QUE É UM CHAMADO DUPLICADO )
	DUPLICADO, 
	
	// SOMENTE PODE SER ENCERRADO PELO CLIENTE
	ENCERRADO;
}
